# This is a basic workflow to help you get started with Actions

name: Test For Jobs & outputs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      new: ${{ steps.step1.outputs.new_tag }}
      current: ${{ steps.step1.outputs.tag }}
    steps:
      - id: step1
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERBOSE: true
          DRY_RUN: true     
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.current}} ${{needs.job1.outputs.new}}
