name: Build with Maven

on:
  workflow_dispatch:
    inputs:
      skip-tests:
        type: boolean
        description: Skip tests
        required: true
        default: 'true'
  push:
    # ...
  pull_request:
    # ...

jobs:
  build:
    # (...)
    steps:
      - name: Print workflow input variables
        run: |
          echo "Input variable:           ${{ github.event.inputs.skip-tests }}"
          echo "Simple expression:        ${{ github.event.inputs.skip-tests != 'false' }}"
          echo "Quasi-ternary expression: ${{ github.event.inputs.skip-tests != 'false' && 'skipping' || 'executing' }}"
      # (...)
      - name: Build + package, ${{ github.event.inputs.skip-tests != 'false' && 'skipping' || 'executing' }} tests
        run: mvn --errors --batch-mode -DskipTests=${{ github.event.inputs.skip-tests != 'false' }} clean verify
